#!/bin/sh

launchctl unload -w /Library/LaunchDaemons/com.geofferey.autorevssh.plist 2>/dev/null

if [[ $(find /etc/ssh/autorevssh.conf 2>/dev/null) ]]; then
cp /etc/ssh/autorevssh.conf /tmp/autorevssh.conf
fi
